package dev.lumamd.viewer.core;

final class AppStyles {
    private AppStyles() {
    }

    static String css() {
        return ":root{"
                + "--canvas:#0E0D13;--glow:#1B1530;--panel:#16141E;--surface:#1D1A27;"
                + "--raised:#252131;--border:#342E43;--border-soft:rgba(255,255,255,.075);"
                + "--text:#F4F1FA;--muted:#B8B2C5;--tertiary:#817A8E;--accent:#A98AFB;"
                + "--accent-strong:#8E63EE;--accent-soft:rgba(169,138,251,.14);"
                + "--accent-ink:#15101D;"
                + "--success:#79D8B0;--code:#171522;--shadow:rgba(0,0,0,.34);"
                + "--tok-keyword:#D8B4FE;--tok-type:#7DD3FC;--tok-string:#A7E3B4;"
                + "--tok-number:#F4C36A;--tok-literal:#F0A3C1;--tok-comment:#8B8498;"
                + "--tok-variable:#F0A3C1;"
                + "--sans:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Noto Sans',sans-serif;"
                + "--serif:Georgia,'Noto Serif',serif;--mono:'SFMono-Regular',Menlo,monospace"
                + "}"
                + "[data-theme=light]{--canvas:#F3F0F7;--glow:#E7DDF9;--panel:#FCFBFE;"
                + "--surface:#F1EDF6;--raised:#E9E2F2;--border:#DDD5E7;"
                + "--border-soft:rgba(38,29,49,.08);--text:#25212B;--muted:#625B6C;"
                + "--tertiary:#665F70;--accent:#7650C8;--accent-strong:#5F38AE;"
                + "--accent-soft:rgba(118,80,200,.12);--accent-ink:#FFFFFF;"
                + "--success:#287A5D;--code:#F0ECF5;"
                + "--shadow:rgba(43,29,58,.12);--tok-keyword:#6D28D9;--tok-type:#0369A1;"
                + "--tok-string:#18794E;--tok-number:#9A5B00;--tok-literal:#BE185D;"
                + "--tok-comment:#6B6473;--tok-variable:#A21CAF}"
                + "*{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--canvas)}"
                + "body{margin:0;min-height:100vh;-webkit-user-select:none;user-select:none;"
                + "color:var(--text);font-family:var(--sans);"
                + "background:radial-gradient(720px 440px at 50% -180px,var(--glow),transparent 76%),"
                + "var(--canvas);overflow-wrap:anywhere;-webkit-font-smoothing:antialiased}"
                + "a{color:inherit}svg{width:20px;height:20px;fill:none;stroke:currentColor;"
                + "stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}"
                + ".topbar{position:sticky;z-index:20;top:0;padding-top:env(safe-area-inset-top);"
                + "background:color-mix(in srgb,var(--canvas) 94%,transparent);"
                + "border-bottom:1px solid var(--border-soft)}"
                + ".topbar-inner{height:64px;max-width:1120px;margin:auto;padding:0 18px;"
                + "display:flex;align-items:center;justify-content:space-between;gap:14px}"
                + ".brand{min-width:0;min-height:48px;display:flex;align-items:center;gap:11px;"
                + "text-decoration:none}"
                + ".app-mark{width:38px;height:38px;color:var(--accent);stroke:none;"
                + "filter:drop-shadow(0 8px 20px var(--accent-soft))}"
                + ".brand-copy{display:flex;flex-direction:column;gap:2px}.brand-copy strong{"
                + "font-size:15px;letter-spacing:-.01em}.brand-copy small{font-size:10px;"
                + "letter-spacing:.07em;text-transform:uppercase;color:var(--tertiary);"
                + "display:flex;align-items:center;gap:5px}.brand-copy i{width:6px;height:6px;"
                + "border-radius:50%;background:var(--success);box-shadow:0 0 0 3px color-mix("
                + "in srgb,var(--success) 14%,transparent)}"
                + ".top-actions,.hero-actions{display:flex;align-items:center;gap:9px}"
                + ".button,.icon-button{min-height:48px;display:inline-flex;align-items:center;"
                + "justify-content:center;text-decoration:none;border:1px solid var(--border);"
                + "border-radius:14px;font-size:14px;font-weight:700;transition:background .16s,"
                + "border-color .16s,transform .09s;outline:none}.button:active,.icon-button:active,"
                + ".tool-dock a:active{transform:translateY(1px)}.button:focus-visible,"
                + ".icon-button:focus-visible,.tool-dock a:focus-visible{box-shadow:0 0 0 2px "
                + "var(--canvas),0 0 0 4px var(--accent)}"
                + ".button{padding:0 16px;gap:8px}.button.primary{border-color:transparent;"
                + "background:var(--accent);color:var(--accent-ink);"
                + "box-shadow:0 8px 26px var(--accent-soft)}"
                + ".button.primary:active{background:var(--accent-strong);color:white}"
                + ".button.ghost,.button.secondary,.icon-button{background:var(--surface);"
                + "color:var(--text)}.icon-button{width:48px;padding:0}"
                + ".welcome{width:min(100%,980px);min-height:calc(100vh - 65px - env("
                + "safe-area-inset-top));margin:auto;padding:56px 18px 34px;display:flex;"
                + "flex-direction:column;justify-content:center}.hero{max-width:720px}"
                + ".eyebrow{font-size:11px;font-weight:800;letter-spacing:.14em;color:var(--muted);"
                + "display:flex;align-items:center;gap:9px}.eyebrow>span{display:block;width:22px;"
                + "height:1px;background:var(--accent)}.hero h1{font-family:var(--serif);"
                + "font-size:clamp(42px,10vw,72px);line-height:1.04;letter-spacing:-.035em;"
                + "margin:18px 0 20px;text-wrap:balance}.hero-copy{max-width:600px;margin:0;"
                + "font-size:18px;line-height:1.65;color:var(--muted)}.hero-actions{margin-top:28px}"
                + ".feature-panel{margin-top:52px;padding:10px 22px;border:1px solid var(--border-soft);"
                + "border-radius:28px;background:linear-gradient(145deg,color-mix(in srgb,"
                + "var(--panel) 96%,var(--accent) 4%),var(--panel));box-shadow:0 28px 80px var(--shadow)}"
                + ".feature{display:grid;grid-template-columns:48px 1fr;gap:14px;padding:20px 0;"
                + "border-bottom:1px solid var(--border-soft)}.feature:last-child{border-bottom:0}"
                + ".feature-icon{width:44px;height:44px;border-radius:14px;background:var(--accent-soft);"
                + "color:var(--accent);display:grid;place-items:center}.feature h2{font-size:15px;"
                + "margin:1px 0 5px}.feature p{font-size:13px;line-height:1.55;color:var(--muted);"
                + "margin:0}.privacy-note{display:flex;align-items:center;justify-content:center;"
                + "gap:7px;margin:72px 0 24px;color:var(--muted);font-size:12px}"
                + ".privacy-note svg{width:15px;height:15px}"
                + ".reader-wrap{width:min(100%,920px);margin:auto;padding:32px 10px 126px}"
                + ".document-head{padding:0 4px 22px}.document-head h1{font-family:var(--serif);"
                + "font-size:clamp(34px,8vw,52px);line-height:1.08;letter-spacing:-.03em;"
                + "margin:14px 0 18px}.document-meta{display:flex;flex-wrap:wrap;gap:9px 16px;"
                + "color:var(--tertiary);font-size:12px;font-weight:650}.document-meta span{"
                + "display:inline-flex;align-items:center;gap:6px}.document-meta svg{width:14px;height:14px}"
                + ".reader-surface{-webkit-user-select:text;user-select:text;padding:24px 16px;"
                + "border:1px solid var(--border-soft);"
                + "border-radius:24px;background:var(--panel);box-shadow:0 24px 70px var(--shadow);"
                + "font-size:calc(17px * var(--type-scale));line-height:1.72}"
                + ".reader-surface>:first-child{margin-top:0}.reader-surface>:last-child{margin-bottom:0}"
                + ".reader-surface h1,.reader-surface h2{font-family:var(--serif);letter-spacing:-.02em}"
                + ".reader-surface h1{font-size:calc(34px * (1 + (var(--type-scale) - 1)*.5));"
                + "line-height:1.18;margin:0 0 24px}.reader-surface h2{font-size:calc(25px * "
                + "(1 + (var(--type-scale) - 1)*.5));line-height:1.3;margin:38px 0 14px}"
                + ".reader-surface h3{font-size:calc(19px * (1 + (var(--type-scale) - 1)*.5));"
                + "line-height:1.35;margin:30px 0 12px}.reader-surface h4,.reader-surface h5,"
                + ".reader-surface h6{margin:26px 0 10px}.reader-surface p{margin:0 0 18px}"
                + ".reader-surface strong{font-weight:750}.reader-surface a{color:var(--accent);"
                + "text-decoration-color:color-mix(in srgb,var(--accent) 42%,transparent);"
                + "text-underline-offset:3px}.reader-surface ul,.reader-surface ol{padding-left:25px;"
                + "margin:0 0 20px}.reader-surface li{padding-left:4px;margin:7px 0}"
                + ".reader-surface li::marker{color:var(--accent)}.reader-surface .task{"
                + "list-style:none;margin-left:-24px;display:flex;align-items:flex-start;gap:10px}"
                + ".checkbox{width:19px;height:19px;flex:0 0 19px;margin-top:5px;border:1px solid "
                + "var(--border);border-radius:6px;display:grid;place-items:center;font-size:12px;"
                + "color:#15101D}.task.done .checkbox{background:var(--success);border-color:var(--success)}"
                + ".reader-surface blockquote{margin:24px 0;padding:16px 18px;border-left:3px solid "
                + "var(--accent);border-radius:0 14px 14px 0;background:var(--accent-soft);color:var(--muted)}"
                + ".reader-surface blockquote p{margin:0}.reader-surface code{font-family:var(--mono);"
                + "font-size:.86em;background:var(--code);padding:.18em .4em;border:1px solid "
                + "var(--border-soft);border-radius:6px}.reader-surface pre{position:relative;"
                + "overflow:auto;margin:24px 0;padding:22px 18px 18px;border:1px solid var(--border-soft);"
                + "border-radius:16px;background:var(--code)}.reader-surface pre[data-language]::before{"
                + "content:attr(data-language);display:block;margin:-8px 0 12px;color:var(--tertiary);"
                + "font:700 10px/1 var(--sans);letter-spacing:.12em;text-transform:uppercase}"
                + ".reader-surface pre code{padding:0;border:0;background:none;white-space:pre}"
                + ".tok-keyword{color:var(--tok-keyword);font-weight:650}.tok-type{color:var(--tok-type)}"
                + ".tok-string{color:var(--tok-string)}.tok-number{color:var(--tok-number)}"
                + ".tok-literal,.tok-variable{color:var(--tok-literal)}.tok-comment{"
                + "color:var(--tok-comment);font-style:italic}"
                + ".table-scroll{overflow-x:auto;margin:24px 0;border:1px solid var(--border-soft);"
                + "border-radius:14px}.reader-surface table{width:100%;border-collapse:collapse;"
                + "font-size:.9em}.reader-surface th,.reader-surface td{padding:12px 14px;"
                + "border-bottom:1px solid var(--border-soft);text-align:left;white-space:nowrap}"
                + ".reader-surface th{background:var(--surface);font-size:.78em;letter-spacing:.05em;"
                + "text-transform:uppercase}.reader-surface tr:last-child td{border-bottom:0}"
                + ".reader-surface hr{border:0;border-top:1px solid var(--border);margin:38px 0}"
                + ".reader-surface img{max-width:100%;height:auto;border-radius:14px}"
                + ".math-inline{display:inline;white-space:nowrap;vertical-align:-.08em;"
                + "color:color-mix(in srgb,var(--text) 88%,var(--accent) 12%)}"
                + ".math-block{display:flex;justify-content:center;overflow-x:auto;margin:26px 0;"
                + "padding:22px 18px;"
                + "border:1px solid var(--border-soft);border-radius:16px;background:var(--surface);"
                + "text-align:center;font-size:1.2em}"
                + ".math-inline math,.math-block math{font-family:'STIX Two Math','Cambria Math',"
                + "'Times New Roman',serif;color:var(--text);font-size:1.06em}"
                + ".math-inline math{display:inline math}.math-block math{display:block math;"
                + "min-width:max-content}.math-block mtable{margin-inline:auto}"
                + ".math-inline mtext,.math-block mtext{font-family:var(--sans);font-size:.9em}"
                + ".math-inline mfrac,.math-block mfrac{padding-inline:.08em}"
                + ".math-inline mtd,.math-block mtd{padding:.12em .36em}"
                + ".math-inline .math-fence mtd,.math-block .math-fence mtd{"
                + "padding:0 .03em;line-height:.72}"
                + ".math-fence-mirror{display:inline-block;transform:scaleX(-1)}"
                + ".footnote-ref{margin-left:.12em;font:750 .72em/1 var(--sans);vertical-align:super}"
                + ".reader-surface .footnote-ref a{text-decoration:none;padding:.12em .18em;"
                + "border-radius:5px;background:var(--accent-soft);scroll-margin-top:120px}"
                + ".footnotes{margin-top:48px;"
                + "color:var(--muted);font-size:.88em}.footnotes hr{margin-bottom:20px}"
                + ".footnotes ol{padding-left:26px}.footnotes li{padding-left:6px;margin:14px 0;"
                + "scroll-margin-top:92px}.footnotes li:target{border-radius:8px;"
                + "background:var(--accent-soft)}.footnote-backlinks{display:inline-flex;gap:3px;"
                + "margin-left:8px}.reader-surface .footnote-backref{display:inline-flex;"
                + "align-items:center;justify-content:center;min-width:28px;min-height:28px;"
                + "text-decoration:none;border-radius:8px;background:var(--surface);font-weight:800}"
                + ".empty-state{min-height:420px;display:flex;flex-direction:column;align-items:center;"
                + "justify-content:center;text-align:center;padding:40px}.empty-icon{width:62px;"
                + "height:74px;border:2px solid var(--border);border-radius:10px;position:relative;"
                + "margin-bottom:20px}.empty-icon::after{content:'';position:absolute;left:15px;"
                + "right:15px;top:24px;height:2px;background:var(--accent);box-shadow:0 10px 0 "
                + "var(--border)}.empty-state h2{margin:0 0 8px}.empty-state p{max-width:360px;"
                + "color:var(--muted);margin:0 0 22px}"
                + ".tool-dock{position:fixed;z-index:18;left:50%;bottom:max(16px,env("
                + "safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:4px;padding:6px;"
                + "border:1px solid var(--border-soft);border-radius:20px;background:var(--surface);"
                + "box-shadow:0 0 0 8px color-mix(in srgb,var(--canvas) 90%,transparent),"
                + "0 18px 60px var(--shadow)}.tool-dock a{width:66px;min-height:58px;"
                + "border-radius:15px;text-decoration:none;color:var(--muted);display:flex;"
                + "flex-direction:column;align-items:center;justify-content:center;gap:3px;"
                + "font-size:12px;font-weight:750;transition:background .16s,color .16s,transform .09s}"
                + ".tool-dock a:active,.tool-dock a:hover{background:var(--raised);color:var(--text)}"
                + ".tool-dock svg{width:19px;height:19px}"
                + ".outline{position:fixed;z-index:30;inset:0;visibility:hidden;opacity:0;"
                + "background:rgba(4,3,7,.68);padding:calc(24px + env(safe-area-inset-top)) 18px "
                + "calc(24px + env(safe-area-inset-bottom));display:flex;align-items:flex-end;"
                + "transition:opacity .18s}.outline:target{visibility:visible;opacity:1}"
                + ".outline-card{width:min(100%,520px);max-height:min(74vh,680px);overflow:auto;"
                + "margin:0 auto;padding:20px;border:1px solid var(--border);border-radius:24px;"
                + "background:var(--panel);box-shadow:0 30px 100px rgba(0,0,0,.5)}"
                + ".outline-head{display:flex;justify-content:space-between;align-items:flex-start;"
                + "padding-bottom:14px;border-bottom:1px solid var(--border-soft)}"
                + ".outline-head .eyebrow{font-size:9px}.outline-head h2{font-family:var(--serif);"
                + "font-size:24px;margin:5px 0 0}.outline nav{display:flex;flex-direction:column;"
                + "padding-top:10px}.outline nav>a{padding:12px 10px;text-decoration:none;"
                + "border-radius:10px;color:var(--muted);font-size:14px}.outline nav>a:active{"
                + "background:var(--accent-soft);color:var(--text)}.outline nav .level-2{padding-left:24px}"
                + ".outline nav .level-3,.outline nav .level-4,.outline nav .level-5,"
                + ".outline nav .level-6{padding-left:38px}.outline-empty{color:var(--tertiary);"
                + "font-size:13px;padding:10px}"
                + ".actions-sheet{position:fixed;z-index:36;inset:0;visibility:hidden;opacity:0;"
                + "background:rgba(4,3,7,.72);padding:calc(24px + env(safe-area-inset-top)) 14px "
                + "calc(18px + env(safe-area-inset-bottom));display:flex;align-items:flex-end;"
                + "transition:opacity .18s}.actions-sheet:target{visibility:visible;opacity:1}"
                + ".actions-card{width:min(100%,520px);margin:0 auto;padding:20px;"
                + "border:1px solid var(--border);border-radius:26px;background:var(--panel);"
                + "box-shadow:0 30px 100px rgba(0,0,0,.5)}.actions-head{display:flex;"
                + "align-items:flex-start;justify-content:space-between;padding-bottom:14px;"
                + "border-bottom:1px solid var(--border-soft)}.actions-head .eyebrow{font-size:9px}"
                + ".actions-head h2{margin:5px 0 0;font:700 26px/1.1 var(--serif)}"
                + ".action-list{display:flex;flex-direction:column;padding-top:8px}.action-item{"
                + "min-height:76px;display:flex;align-items:center;gap:14px;padding:10px 8px;"
                + "border-radius:16px;color:var(--text);text-decoration:none}.action-item:active{"
                + "background:var(--accent-soft)}.action-icon{width:46px;height:46px;flex:0 0 46px;"
                + "display:flex;align-items:center;justify-content:center;border-radius:14px;"
                + "background:var(--accent-soft);color:var(--accent)}.action-icon svg{width:22px;"
                + "height:22px}.action-item>span:last-child{display:flex;min-width:0;"
                + "flex-direction:column;gap:3px}.action-item strong{font-size:15px}"
                + ".action-item small{color:var(--muted);font-size:12px;line-height:1.45}"
                + "@media(min-width:650px){.welcome{padding-left:32px;padding-right:32px}"
                + ".feature-panel{display:grid;grid-template-columns:repeat(3,1fr);gap:0;padding:8px}"
                + ".feature{display:block;padding:20px;border-bottom:0;border-right:1px solid "
                + "var(--border-soft)}.feature:last-child{border-right:0}.feature-icon{margin-bottom:16px}"
                + ".reader-wrap{padding-left:32px;padding-right:32px}.reader-surface{padding:48px}}"
                + "@media(min-width:920px){.reader-wrap{width:min(100%,1120px);padding-right:300px;"
                + "transform:translateX(130px)}.outline{z-index:10;visibility:visible;opacity:1;"
                + "pointer-events:none;background:none;padding:136px max(22px,calc((100vw - 1080px)/2));"
                + "align-items:flex-start;justify-content:flex-end}.outline-card{width:250px;margin:0;"
                + "pointer-events:auto;box-shadow:none;background:transparent;border-color:transparent;"
                + "padding:0}.outline-head .icon-button{display:none}.tool-dock{left:calc(50% + 120px)}}"
                + "@media(max-width:420px){.brand-copy small{display:none}.button{padding:0 14px}"
                + ".hero-actions{align-items:stretch;"
                + "flex-direction:column}.hero-actions .button{width:100%}}"
                + "@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;"
                + "transition:none!important;animation:none!important}}";
    }
}
